package com.model.admin;
// Generated Jun 8, 2015 10:08:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private int idUser;
     private String nama;
     private String jk;
     private String alamat;
     private String email;
     private String phone;
     private String username;
     private String password;

    public Admin() {
    }

    public Admin(String nama, String jk, String alamat, String email, String phone, String username, String password) {
       this.nama = nama;
       this.jk = jk;
       this.alamat = alamat;
       this.email = email;
       this.phone = phone;
       this.username = username;
       this.password = password;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getJk() {
        return this.jk;
    }
    
    public void setJk(String jk) {
        this.jk = jk;
    }
    
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
}


